sudo: required
services:
  - docker
before_install:
  - docker build -t tundaey/split.webapp -f Dockerfile.dev .
script:
  - docker run tundaey/split.webapp npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: splitapp
  env: "Splitapp-env"
  bucket_name: "elasticbeanstalk-us-west-2-227599607936"
  bucket_path: "splitapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"